"""Emit the seed SQL that Person B loads into Supabase.

Deliberately plain INSERTs with ON CONFLICT, not a pg_dump: the team needs to
read, diff and hand-edit this during a 3-hour build, and a row that looks wrong
on screen should be fixable without rerunning the pipeline.
"""
from __future__ import annotations

import json
import uuid
from datetime import date
from typing import Any, Iterable, Optional

from prep import config as C

NAMESPACE = uuid.NAMESPACE_URL


def tender_uuid(ted_id: str) -> str:
    return str(uuid.uuid5(NAMESPACE, f"procurement-passport:tender:{ted_id}"))


def q(v: Any) -> str:
    """SQL literal. Everything user-visible passes through here, and the
    doubled quote is what keeps a Dutch clause containing an apostrophe from
    breaking the seed file."""
    if v is None or v == "":
        return "null"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return repr(v)
    if isinstance(v, date):
        return f"'{v.isoformat()}'"
    if isinstance(v, (dict, list)):
        return "'" + json.dumps(v, ensure_ascii=False).replace("'", "''") + "'::jsonb"
    return "'" + str(v).replace("'", "''") + "'"


def arr(vals: Optional[Iterable[str]]) -> str:
    vals = list(vals or [])
    if not vals:
        return "'{}'"
    inner = ",".join('"' + str(v).replace('"', '\\"') + '"' for v in vals)
    return "'{" + inner + "}'"


def header(title: str) -> str:
    return (f"-- {title}\n"
            f"-- Generated by prep.py on {date.today().isoformat()}. "
            f"Safe to re-run.\n-- Hand edits survive: change the row, not the script,"
            f" if the demo needs it.\n\n")


# ------------------------------------------------------------------ tenders
def tenders_sql(tenders: list[dict]) -> str:
    out = [header("Tenders -- 12 open Dutch IT tenders from TED")]
    out.append("begin;\n")
    for t in tenders:
        out.append(
            "insert into tenders (id, ted_id, title, buyer, value_eur, deadline, cpv,\n"
            "                     joint_bids_allowed, subcontracting_allowed, portal,\n"
            "                     documents_url, source_url, pack_status, notes)\n"
            f"values ({q(t['id'])}, {q(t['ted_id'])}, {q(t['title'])}, {q(t['buyer'])},\n"
            f"        {q(t.get('value_eur'))}, {q(t.get('deadline'))}, {arr(t.get('cpv'))},\n"
            f"        {q(t.get('joint_bids_allowed', True))}, {q(t.get('subcontracting_allowed', True))},\n"
            f"        {q(t.get('portal'))}, {q(t.get('documents_url'))}, {q(t['source_url'])},\n"
            f"        {q(t.get('pack_status', 'none'))}, {q(t.get('notes'))})\n"
            "on conflict (ted_id) do update set\n"
            "  title = excluded.title, buyer = excluded.buyer,\n"
            "  value_eur = excluded.value_eur, deadline = excluded.deadline,\n"
            "  cpv = excluded.cpv,\n"
            "  joint_bids_allowed = excluded.joint_bids_allowed,\n"
            "  subcontracting_allowed = excluded.subcontracting_allowed,\n"
            "  pack_status = excluded.pack_status, notes = excluded.notes;\n")
    out.append("\ncommit;\n")
    return "\n".join(out)


# ------------------------------------------------------------- requirements
def requirements_sql(rows: list[dict]) -> str:
    out = [header("Requirements -- extracted from the tender document packs")]
    out.append("begin;\n")
    out.append("-- Rebuilt wholesale: re-running extraction must not leave "
               "stale rows behind.\ndelete from requirements;\n")
    for r in rows:
        out.append(
            "insert into requirements (tender_id, req_type, key, operator, threshold_num,\n"
            "                          threshold_text, window_years, public_sector_required,\n"
            "                          knockout, lot, clause_ref, source_quote, page,\n"
            "                          confidence, source_doc)\n"
            f"values ({q(r['tender_id'])}, {q(r['req_type'])}, {q(r['key'])}, {q(r['operator'])},\n"
            f"        {q(r.get('threshold_num'))}, {q(r.get('threshold_text'))}, {q(r.get('window_years'))},\n"
            f"        {q(r.get('public_sector_required', False))}, {q(r.get('knockout', True))},\n"
            f"        {q(r.get('lot'))}, {q(r.get('clause_ref'))}, {q(r['source_quote'])},\n"
            f"        {q(r.get('page'))}, {q(r.get('confidence', 'medium'))}, {q(r.get('source_doc'))});\n")
    out.append("\ncommit;\n")
    return "\n".join(out)


# ----------------------------------------------------------------- partners
def partners_sql(partners: list[dict], facts: list[dict]) -> str:
    out = [header("Partner candidates -- winners of NL public IT contracts on TED")]
    out.append("begin;\n")
    for p in partners:
        out.append(
            "insert into companies (id, name, is_demo, country, slug)\n"
            f"values ({q(p['id'])}, {q(p['name'])}, false, 'NL', {q(p['slug'])})\n"
            "on conflict (id) do update set name = excluded.name;\n")
        # References come from published award notices, so they are `official`.
        out.append(f"delete from company_references where company_id = {q(p['id'])};")
        for r in p.get("references", []):
            out.append(
                "insert into company_references (company_id, buyer, title, public_sector, cpv,\n"
                "                  value_eur, end_date, trust, source_url)\n"
                f"values ({q(p['id'])}, {q(r['buyer'])}, {q(r.get('title'))},\n"
                f"        {q(r.get('public_sector', True))}, {q(r.get('cpv'))},\n"
                f"        {q(r.get('value_eur'))}, {q(r.get('end_date'))}, 'official',\n"
                f"        {q(r.get('source_url'))});")
        out.append("")

    if facts:
        out.append("\n-- Certifications read off the partner's own website. These are\n"
                   "-- `claim`, never `official`: nobody audited them for us, and the\n"
                   "-- UI badges them differently for exactly that reason.")
        for f in facts:
            out.append(
                "insert into capabilities (company_id, req_type, key, value_num, value_text,\n"
                "                          trust, source_url, source_quote)\n"
                f"values ({q(f['company_id'])}, {q(f['req_type'])}, {q(f['key'])},\n"
                f"        {q(f.get('value_num'))}, {q(f.get('value_text'))}, 'claim',\n"
                f"        {q(f.get('source_url'))}, {q(f.get('source_quote'))})\n"
                "on conflict (company_id, req_type, key) do update set\n"
                "  source_url = excluded.source_url, source_quote = excluded.source_quote;")
    out.append("\ncommit;\n")
    return "\n".join(out)


# ------------------------------------------------------------ demo company
DEMO_PREAMBLE = """-- The demo company.
--
-- Fictional, but shaped like a real Dutch IT SME: profitable, competent,
-- certified for quality but not for security, with a short public track
-- record. That shape is the whole point -- it is the profile that loses
-- tenders for reasons nobody told it about.
--
-- Generated from data/curated/demo_company.json. Edit that file, not this one,
-- then re-run `python -m prep.run emit`. Tuning the demo profile so the gaps
-- spread across the ladder is fair game; tuning extracted requirements is not.

"""


def demo_company_sql(c: dict) -> str:
    cid = c["id"]
    out = [DEMO_PREAMBLE, "begin;\n"]
    out.append(
        "insert into companies (id, name, is_demo, country, slug, prefs)\n"
        f"values ({q(cid)}, {q(c['name'])}, true, {q(c.get('country', 'NL'))},\n"
        f"        {q(c.get('slug'))}, {q(c.get('prefs', {}))})\n"
        "on conflict (id) do update set name = excluded.name, prefs = excluded.prefs;\n")

    out.append(f"delete from capabilities where company_id = {q(cid)};\n")
    for cap in c.get("capabilities", []):
        out.append(
            "insert into capabilities (company_id, req_type, key, value_num, value_text,\n"
            "                          valid_until, trust, source_quote)\n"
            f"values ({q(cid)}, {q(cap['req_type'])}, {q(cap['key'])}, {q(cap.get('value_num'))},\n"
            f"        {q(cap.get('value_text'))}, {q(cap.get('valid_until'))},\n"
            f"        {q(cap.get('trust', 'verified'))}, {q(cap.get('source_quote'))});")

    out.append(f"\ndelete from company_references where company_id = {q(cid)};\n")
    for r in c.get("references", []):
        out.append(
            "insert into company_references (company_id, buyer, title, public_sector, cpv,\n"
            "                  value_eur, end_date, trust)\n"
            f"values ({q(cid)}, {q(r['buyer'])}, {q(r.get('title'))},\n"
            f"        {q(r.get('public_sector', True))}, {q(r.get('cpv'))},\n"
            f"        {q(r.get('value_eur'))}, {q(r.get('end_date'))},\n"
            f"        {q(r.get('trust', 'verified'))});")
    out.append("\ncommit;\n")
    return "\n".join(out)
