"""Generate supabase/migrations/ from the sql/ sources.

One source of truth. sql/*.sql stays the thing you read and hand-edit (and can
paste straight into the Supabase SQL editor); the migrations directory is the
CLI's view of the same statements, timestamped in dependency order.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MIG = ROOT / "supabase" / "migrations"

# (timestamp, name, [source files]) -- order is dependency order.
PLAN = [
    ("20260923000001", "schema",   ["sql/01_schema.sql"]),
    ("20260923000002", "ladder",   ["sql/02_ladder.sql"]),
    ("20260923000003", "llm",      ["sql/08_llm.sql"]),
    ("20260923000004", "rls",      ["sql/07_rls.sql"]),
]


def main() -> int:
    MIG.mkdir(parents=True, exist_ok=True)
    for stamp, name, sources in PLAN:
        body = [f"-- Generated by tools/make_migrations.py from {', '.join(sources)}.",
                "-- Edit the source file, not this one, then re-run the generator.", ""]
        for s in sources:
            body.append((ROOT / s).read_text(encoding="utf-8"))
        out = MIG / f"{stamp}_{name}.sql"
        out.write_text("\n".join(body), encoding="utf-8")
        print(f"  {out.relative_to(ROOT)}")
    print(f"{len(PLAN)} migrations written")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
