"""Concatenate every seed file, in load order, into out/00_bundle.sql.

Pasting six files into the Supabase SQL editor in the right order is the kind
of thing that goes wrong at minute 150. One file cannot be pasted out of order.
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ORDER = ["sql/01_schema.sql", "sql/02_ladder.sql", "sql/03_demo_company.sql",
         "out/04_tenders.sql", "out/05_requirements.sql", "out/06_partners.sql",
         "sql/08_llm.sql", "sql/07_rls.sql"]
HEAD = """-- =====================================================================
-- Procurement Passport -- complete seed bundle
--
-- Everything in load order, for pasting into the Supabase SQL editor in one
-- go. Generated by tools/make_bundle.py; edit the source files, not this one.
-- Safe to re-run.
-- =====================================================================

"""

def main() -> int:
    parts = [HEAD]
    for f in ORDER:
        parts.append(f"\n-- ############ {f} ############\n")
        parts.append((ROOT / f).read_text(encoding="utf-8"))
    out = ROOT / "out" / "00_bundle.sql"
    out.write_text("\n".join(parts), encoding="utf-8")
    print(f"wrote {out.relative_to(ROOT)} ({out.stat().st_size // 1024} KB)")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
