-- Generated by tools/make_migrations.py from sql/01_schema.sql.
-- Edit the source file, not this one, then re-run the generator.

-- Procurement Passport -- schema contract.
--
-- Person B owns the Supabase project; this file is the shape prep.py writes
-- into and the shape /evaluate and the Lovable app read out of. If a column
-- changes here it has to change in prep/models.py too -- they are the same
-- vocabulary on two sides of the wire.
--
-- Safe to re-run.

-- No extension needed: gen_random_uuid() is core Postgres since 13, and
-- Supabase runs 15+. Requiring pgcrypto only breaks the seed on builds that
-- ship without it.

-- ---------------------------------------------------------------- companies
create table if not exists companies (
  id          uuid primary key default gen_random_uuid(),
  name        text not null,
  is_demo     boolean not null default false,
  country     text not null default 'NL',
  legal_form  text,
  slug        text unique,
  -- Partner exclusions live in their own column as well as inside prefs: the
  -- rules engine reads prefs, but a uuid[] is what you can actually join on.
  excluded_partners uuid[] not null default '{}',
  prefs       jsonb not null default '{
                 "allow_certification": true,
                 "allow_partners": true,
                 "partner_min_contract_value_eur": 0,
                 "excluded_partners": []
               }'::jsonb,
  created_at  timestamptz not null default now()
);

-- What a company can prove. `trust` is load-bearing: the UI badges it and the
-- partner score weights it, so never upgrade a claim to official in the data.
create table if not exists capabilities (
  id           uuid primary key default gen_random_uuid(),
  company_id   uuid not null references companies(id) on delete cascade,
  req_type     text not null check (req_type in
                 ('turnover','certification','references','insurance',
                  'staff_language','local_presence','other')),
  key          text not null,
  value_num    numeric,
  value_text   text,
  valid_until  date,
  trust        text not null default 'claim'
                 check (trust in ('verified','official','claim')),
  source_url   text,
  source_quote text,
  unique (company_id, req_type, key)
);
create index if not exists capabilities_company_idx on capabilities(company_id);

-- Past projects. For partners these come straight from TED award notices.
create table if not exists company_references (
  id            uuid primary key default gen_random_uuid(),
  company_id    uuid not null references companies(id) on delete cascade,
  buyer         text not null,
  title         text,
  description   text,
  public_sector boolean not null default true,
  cpv           text,
  value_eur     numeric,
  end_date      date,
  trust         text not null default 'official'
                  check (trust in ('verified','official','claim')),
  source_url    text
);
create index if not exists company_references_company_idx on company_references(company_id);

-- ------------------------------------------------------------------ tenders
create table if not exists tenders (
  id                     uuid primary key default gen_random_uuid(),
  ted_id                 text unique not null,
  title                  text not null,
  buyer                  text not null,
  value_eur              numeric,
  deadline               date,
  cpv                    text[],
  joint_bids_allowed     boolean not null default true,
  subcontracting_allowed boolean not null default true,
  portal                 text,
  documents_url          text,
  source_url             text not null,
  pack_status            text not null default 'none',
  notes                  text
);

-- One row per extracted requirement. Every row cites its clause: the UI shows
-- source_quote + page on click, which is what makes a verdict auditable.
create table if not exists requirements (
  id                     uuid primary key default gen_random_uuid(),
  tender_id              uuid not null references tenders(id) on delete cascade,
  req_type               text not null check (req_type in
                           ('turnover','certification','references','insurance',
                            'staff_language','local_presence','other')),
  key                    text not null,
  operator               text not null check (operator in
                           ('gte','lte','eq','exists','count_gte')),
  threshold_num          numeric,
  threshold_text         text,
  window_years           int,
  -- A reference clause often carries both a count and a floor on contract
  -- value ("twee referenties van elk minimaal EUR 250.000").
  min_value_eur          numeric,
  public_sector_required boolean not null default false,
  knockout               boolean not null default true,
  lot                    text,
  clause_ref             text,
  source_quote           text not null,
  page                   int,
  confidence             text not null default 'medium'
                           check (confidence in ('high','medium','low')),
  source_doc             text
);
create index if not exists requirements_tender_idx on requirements(tender_id);

-- ------------------------------------------------------------------- ladder
-- Static. max_days is what the deadline check compares against; levels 5 and 6
-- are null because they cannot be closed alone before any realistic deadline.
create table if not exists ladder (
  level     int primary key,
  label     text not null,
  typical   text not null,
  max_days  int
);

-- ------------------------------------------------------- evaluation outputs
create table if not exists results (
  id              uuid primary key default gen_random_uuid(),
  company_id      uuid not null references companies(id) on delete cascade,
  requirement_id  uuid not null references requirements(id) on delete cascade,
  status          text not null check (status in ('pass','gap','review')),
  gap_level       int references ladder(level),
  fixable_in_time boolean,
  reason          text,
  unique (company_id, requirement_id)
);
create index if not exists results_company_idx on results(company_id);

create table if not exists tender_status (
  id         uuid primary key default gen_random_uuid(),
  company_id uuid not null references companies(id) on delete cascade,
  tender_id  uuid not null references tenders(id) on delete cascade,
  label      text not null check (label in
               ('ready','reachable_fix','reachable_partner','future','out_of_reach')),
  met        int not null default 0,
  total      int not null default 0,
  gaps       jsonb not null default '[]'::jsonb,
  unique (company_id, tender_id)
);

create table if not exists partner_recs (
  id           uuid primary key default gen_random_uuid(),
  company_id   uuid not null references companies(id) on delete cascade,
  tender_id    uuid not null references tenders(id) on delete cascade,
  partner_id   uuid not null references companies(id) on delete cascade,
  rank         int not null,
  score        numeric not null,
  gaps_covered text[] not null default '{}',
  joint_met    int not null default 0,
  joint_total  int not null default 0,
  role         text,
  evidence     jsonb not null default '[]'::jsonb,
  unique (company_id, tender_id, partner_id)
);

-- --------------------------------------------------------------- aggregates
-- Per gap key: how many open tenders it blocks, how much value, and how many
-- it would unlock ON ITS OWN. The last column counts only tenders where this
-- is the sole gap, so the headline number can never overclaim.
create or replace view gap_summary as
with gaps as (
  select r.company_id,
         req.key                                            as gap_key,
         r.gap_level                                        as ladder_level,
         t.id                                               as tender_id,
         t.value_eur,
         count(*) over (partition by r.company_id, t.id)     as gaps_on_tender
  from results r
  join requirements req on req.id = r.requirement_id
  join tenders t        on t.id  = req.tender_id
  where r.status = 'gap'
)
select company_id,
       gap_key,
       max(ladder_level)                                           as ladder_level,
       count(distinct tender_id)                                   as tenders_blocked,
       coalesce(sum(value_eur), 0)                                 as value_blocked,
       count(distinct tender_id) filter (where gaps_on_tender = 1) as tenders_unlocked_alone,
       coalesce(sum(value_eur) filter (where gaps_on_tender = 1), 0)
                                                                   as value_unlocked_alone
from gaps
group by company_id, gap_key;

-- Views default to the creator's permissions, which bypasses the caller's RLS.
-- Everything behind gap_summary is public-read anyway, so nothing leaks today,
-- but a view that ignores RLS is a trap for whoever adds a private table to it
-- later. Supabase's linter flags it as an ERROR, and it is right to.
alter view gap_summary set (security_invoker = true);
